TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += knrk6.db
DATA += knrk6.proto

#=======================================
include $(TOP)/configure/RULES
